### ISSUE TITLE
Announce atd 2.0.0 (json adapters)

### ISSUE THREAD

**Issue by mjambon** [ahrefs/atd#127]
Pending opam-repository merge https://github.com/ocaml/opam-repository/pull/12107

This release provides json adapters, which are minimally documented in atdgen's reference manual. atdgen-runtime comes with some useful modules and functors, like the one that deals with objects like `{"type": "event", ... }`. It would be good to show a simple example in the announcement email. The one from the manual may be just fine.

Relevant URLs:
* `<json open_enum>`: https://mjambon.github.io/atdgen-doc/atdgen#field-open_enum
* `<json adapter.ocaml="...">`: https://mjambon.github.io/atdgen-doc/atdgen#field-adapter.ocaml
* source mli for json adapter library: https://github.com/mjambon/atd/blob/master/atdgen-runtime/src/json_adapter.mli

We could use some help for consolidating the docs and exposing the odoc-generated pages. We can apologize and call for help at the same time. The relevant issues are found under the "documentation" tag at:
* https://github.com/mjambon/atd/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation

**Comment by mjambon** [comment]
atd 2.0.0 is now available from opam!

@rgrinberg do you want to make an announcement on https://discuss.ocaml.org/ ?

**Comment by rgrinberg** [comment]
Hmm, so the manual here: http://atd.readthedocs.io/en/latest/ hasn't been updated?

I thought we wouldn't be updating the old man pages anymore. I don't see how we can consolidate API docs and the manual at the moment unfortunately, but I don't think it's so bad if those are separate.

**Comment by mjambon** [comment]
oh yeah, we do generate the manual as a man page. It's not installed by opam and obviously I never used it. Starting work on the translation now (#109).

**Comment by rgrinberg** [comment]
Martin Jambon <notifications@github.com> writes:

> Let me try to clarify the situation.

Okay, thanks. I understand the situation now. Just a couple of notes I'd
like to make documentation:

* Eventually, I expect opam to build and publish odocs for us
  automatically. This has the advantage of having the docs of all
  versioned of the package published. This is why I think we shouldn't
  worry so much about making sense of things here and simply dump the
  output of `$ jbuilder build @doc` for now.

* There's a way to build man pages from .rst docs using sphinx as well:
  http://www.sphinx-doc.org/en/master/man/sphinx-build.html (see the
  groff bit). Maybe it's worth checking out?
