### ISSUE TITLE
atdgen's "ocaml internals" test segfaults on i386

### ISSUE THREAD

**Issue by glondu** [ahrefs/atd#140]
Hello,

atdgen's "ocaml internals" test uses the following pattern:

    let float = ref (Obj.magic 0) in
    float := 4.5

which segfaults on i386. IMHO, this pattern does not make any sense on 32-bit architectures (but i386 is the only failing Debian architecture: https://buildd.debian.org/status/package.php?p=ocaml-atd&suite=unstable).

Cheers,

-- 
Stéphane

**Comment by mjambon** [comment]
There's a [plan to remove the use of Obj.magic](https://github.com/mjambon/atd/issues/92) which will take these bugs and worries away.

**Comment by mjambon** [comment]
This was completed for the JSON backend. It still needs to be done for biniou (#147). Closing to deduplicate.
