### ISSUE TITLE
Installing atd with BuckleScript backend

### ISSUE THREAD

**Issue by shinzui** [ahrefs/atd#171]
Hi,

I'm trying to install the latest atdgen with BuckleScript support in a BuckleScript project which is obviously stuck on OCaml 4.02.3. It does not look like `atd` 2.0.0 is available on this version of the compiler. What's the recommended way to install a version with the BuckleScript backend? 

![image](https://user-images.githubusercontent.com/519/48718104-97108500-ebcf-11e8-8bcb-a2764c5a0913.png)

 EDIT: I updated the screenshot to a clean 4.02.3 opam switch.

**Comment by Khady** [comment]
Easiest solution is probably to install atd from a switch with a recent ocaml. Then the code generated by atd can be compiled by bucklescript/ocaml 4.02.3. You need to install dev version of atd to get the bucklescript generation by the way.

**Comment by shinzui** [comment]
@Khady I misunderstood you then when you said that everything is released on the reason [discourse](https://reasonml.chat/t/sharing-code-with-an-ocaml-native-backend/1216/5). Should your [article](https://tech.ahrefs.com/getting-started-with-atdgen-and-bucklescript-1f3a14004081) be updated to reflect that you need to install atd in a different opam switch?

**Comment by Khady** [comment]
You are right that the article is not correct. It should not mention a 4.02.3 switch. In the article the switch is used only to install atdgen. So the version of ocaml doesn't matter much as long as it is >= 4.03. Will do an update. Thank you!

**Comment by Khady** [comment]
bucklescript is now 4.06 and according to opam health check atdgen works on it. So this problem should be solved.
