### ISSUE TITLE
Ambiguous record fields

### ISSUE THREAD

**Issue by rdavison** [ahrefs/atd#172]
After I made some changes to github.com/andrenth/ocaml-swagger I found that I could no longer compile the library.  That library uses atdgen to convert the swagger json spec to an ocaml data type. However, after my changes, I found that more type annotations were now required.  What I did in order to get the library to compile was to apply a patch ( https://github.com/rdavison/ocaml-swagger/blob/watch/src/patch.txt ) to the generated output.

The easiest way to recreate the bug is by running the following commands:
```
git clone git@github.com:rdavison/ocaml-swagger -b watch
cat /dev/null > ocaml-swagger/src/patch.txt
dune build -p swagger
```

**Comment by mjambon** [comment]
That's interesting. Which version of ocaml are you using? Do you have a minimal atd file that exhibits the problem?

**Comment by rdavison** [comment]
I'm using OCaml 4.06.1, and I do not have a minimal example, however, the instructions above show how to trigger the issue using an existing open source project. I'll admit, I don't really understand why the issue arose in the first place, but I can point out that the difference between when it was working and when it stopped working was after I began using `<json adapter.ocaml="Swagger_util.Adapters.Extensions">` ( https://github.com/rdavison/ocaml-swagger/blob/watch/src/swagger_util.ml#L13 )

**Comment by mjambon** [comment]
The links are dead and there's not enough info here to reproduce the problem.
