### ISSUE TITLE
Allow arguments to adapters

### ISSUE THREAD

**Issue by yonilevy** [ahrefs/atd#184]
[Feature Request]
[Bear with me, as I'm new to yojson/atd and OCaml in general]

I find adapters to be critical when working with external json structures, which I presume is a very common use case. The ability to pass arguments to adapters would make them much more flexible, readable within the .atd context, and allow for reuse and sharing of adapters.

Two use-case examples:
1) The provided `Atdgen_runtime.Json_adapter.Type_field` to take "type" field key as an argument
2) I've written an adapter to "lift" some fields, so `{"a": 1, "b": 2, "c": 3}` when lifting with `"body", ["a"]` would become `{"a": 1, "body": {"b": 2, "c": 3}}` -- it'd be great if i could pass those arguments in the .atd file.

Does that sound reasonable at all?

**Comment by mjambon** [comment]
It seems reasonable to me. Keep in mind that json adapters are a relatively recent feature.

There are a few things to take into account:
* We could support annotations like `<json adapter.ocaml="Lift" adapter.ocaml_param="(\"body\", [\"a\"])">`. In this case, the presence of `ocaml_param` would indicate that the functions `normalize` and `restore` take its value as an extra argument. Another option I can think of would be to support `<json adapter.ocaml_normalize="Lift.normalize \"body\" [\"a\"]" adapter.ocaml_restore="Lift.restore \"body\" [\"a\"]">`.
* Having to escape double quotes isn't very nice but I don't know if there's a better solution without making things too complicated.
* We're short in personnel. If you or someone else could post first a detailed proposal and later the (simple) implementation with documentation, it would be ideal.

**Comment by yonilevy** [comment]
Great!

Your first suggested syntax is what I had in mind, I agree the escaping problem is annoying but that it'd be best to start with that and perhaps improve in the future. I'll try to dive in and see if I can come up with something.

**Comment by mjambon** [comment]
Implemented by https://github.com/ahrefs/atd/pull/232
