### ISSUE TITLE
Error: This kind of expression is not allowed as right-hand side of `let rec'

### ISSUE THREAD

**Issue by pmonson711** [ahrefs/atd#197]
The following atd definition, when generating a json serializers and deserializers produces the error in the title.

```
type a = { bug: variant }

type variant =
  [ B of bool
  | A of a
  ] <json adapter.ocaml="Schema_util.Type_field">
```
```
File "lib/bug_j.ml", line 27, characters 20-451:
27 | ....................(
28 |   Atdgen_runtime.Oj_run.write_with_adapter Schema_util.Type_field.restore (
29 |     fun ob x ->
30 |       match x with
31 |         | `B x ->
...
41 |           ) ob x;
42 |           Bi_outbuf.add_char ob '>'
43 |   )
44 | )
Error: This kind of expression is not allowed as right-hand side of `let rec'
```

The following happens with atdgen version 2.0.0

I'm not sure if this expected to be supported or not.

**Comment by mjambon** [comment]
Thanks for reporting this. This should be supported. It looks like the generated code should have performed an eta-expansion but did not. We're in this situation:
```ocaml
let wrap f n =
  if n > 0 then
    f (n - 1)
  else
    0

let rec f =
  wrap g
and g =
  wrap f
```
which gives the error:
```
  wrap g
  ^^^^^^
Error: This kind of expression is not allowed as right-hand side of `let rec'
```
Instead it should be:
```ocaml
let rec f =
  fun x ->
    (wrap g) x
and g =
  fun x ->
    (wrap f) x
```
which is fine.

Atdgen internally uses a special-purpose annotation in the generated AST for this. This marks expressions that perform a computation like `wrap g` above and should be eta-expanded when they're the right-hand-side of a let-rec binding. This annotation may be missing, misplaced, or ignored.

I'm sorry I don't have the time to work on a fix but I hope this information is helpful to anyone willing to give this a shot.

**Comment by pmonson711** [comment]
Thanks for the quick response. I'm looking to get familiar with the atdget structure, so see if I can help with an MR. 

If I'm following the thought process of eta-expansion, I'll need to follow to logic in `oj_emit.ml`'s `make_ocaml_json_{{writer|reader}}` functions. I was going to start with creating a test case... I'm a bit unfamiliar with the test setup. It seems like the atdgen tests are mostly expect style tests. But I'm unsure if that test format makes sense for this issue.

Any additional guidance is welcome, otherwise I'll see what I can do to address it.
Thanks

**Comment by mjambon** [comment]
Yes, look into `oj_emit.ml` for places that perform "eta-expansion" i.e. search for `eta_expand`. You'll see this:
```ocaml
   let eta_expand = is_rec && not (Ox_emit.is_lambda writer_expr) in
```
This should already do the right thing. What you need is make sure that `Ox_emit.is_lambda writer_expr` will return `true`. Look into `ox_emit.ml` and you'll find this:
```ocaml
let rec is_lambda (l : Indent.t list) =
  match l with
    [] -> false
  | x :: _ ->
      match x with
        Line _ -> false
      | Block l -> is_lambda l
      | Inline l -> is_lambda l
      | Annot ("fun", _) -> true
      | Annot (_, x) -> is_lambda [x]
```
What's relevant is `| Annot ("fun", _) -> true`.

So, wherever an expression is wrapped with the user-provided `restore` or `normalize` functions, the generated code is an `Indent.t list` whose first element should be of the form `Annot ("fun", _)`. I see we have `read_with_adapter` and `write_with_adapter` functions which take care of generating the code. These are the functions you need to modify, I think.

Regarding testing, all you have to do is insert a version of your original `bug.atd` in one of the atd test files and make sure it compiles (the whole thing is a little messy).

**Comment by mjambon** [comment]
For examples, you can look at other places where `Annot ("fun", ...)` nodes are inserted.

**Comment by mjambon** [comment]
Also you can modify the code generator and inspect the generated code to see what it did even if you're not sure what you're doing. A bit of trial-and-error can be useful.

**Comment by pmonson711** [comment]
Thanks again for all the guidance. I went to setup a test and it appears to already be fixed in master. I expect the fix for #133 never made it to opam. I'll my test project with the repo pinned to verify and report back.

Including some info just in case it helps:
```
$ opam --version
2.0.3
```

```
$ opam list -i atdgen
# Packages matching: installed & name-match(atdgen)
# Name # Installed # Synopsis
atdgen 2.0.0       Generates efficient JSON serializers, deserializers and validators
```

But it appears the release was Jun 3rd, while the fix was on the 20th.

**Comment by mjambon** [comment]
Ah, that makes sense. So, what we need a new release of atd.

**Comment by pmonson711** [comment]
Just to follow up, after running the following in a local checkout of the repo at master; everything works as expected in my project.

```
opam pin . 
```

So a new release to opam packages should relieve the issue without depending on the local pin.

**Comment by zindel** [comment]
@pmonson711 I see the latest release was on `Apr 15, 2020` meaning that the fix was released, could you, please, confirm that it works for you?

**Comment by pmonson711** [comment]
I've confirmed the fix
