### ISSUE TITLE
Annotation in the wrong location should be an error

### ISSUE THREAD

**Issue by kittipatv** [ahrefs/atd#204]
I'm new to this library. It took me a while to debug the follow code, as it happily compiles

```
type foo = {
  foo_bar: bool <json name="fooBar">;
}
```

The annotation there has no effect. It would be nice to be warned about that.

```
$ atdgen -version
2.0.0
```

**Comment by zindel** [comment]
That is an interesting one. In your example the annotation belongs to type `bool`, so there is no way now to tell what you wanted exactly. As a human being I totally understand your confusion - been there too.

 The bigger problem though is that we don't have an easy way to check if annotation makes sense at a given position. I'll add the separate issue for that. I think fixing it at a low level will fix your one too. The report could be something like `type annotation <json ...> is not applicable here`
