### ISSUE TITLE
Reserved words handling

### ISSUE THREAD

**Issue by akshimassar** [ahrefs/atd#206]
I tried creating `type object` and atd generated code successfully. Later ocaml threw a syntax error. Would be great to catch such errors on code generation step and have meaningful errors.

**Comment by aij** [comment]
The Scala and Java backends do handle reserved words (eg: https://github.com/ahrefs/atd/blob/8c46ac5f0907d5747ac6cfa9a7dfe2e0c9452c8a/atds/src/atds_names.ml#L39 )

I'm not seeing the same for ocaml though.

**Comment by denis631** [comment]
@akshimassar  @aij the reserved keywords of OCaml are defined here → https://caml.inria.fr/pub/docs/manual-ocaml/lex.html#sec84

**Comment by zindel** [comment]
Actually, I am not sure appending `_` to type names field names is a good idea. It kinda adds implicit behaviour, which might not be desirable/expected. What if we just fail in such cases?
