### ISSUE TITLE
Unnecessary dependency on re in atdgen-runtime?

### ISSUE THREAD

**Issue by Lupus** [ahrefs/atd#211]
I didn't find any uses of `Re` in code, neither I found `re` in dune file:

```
(library
 (name atdgen_runtime)
 (public_name atdgen-runtime)
 (libraries biniou yojson))
```

But `re` is listed in opam file as dependency. Is that expected?

```
depends: [
  "ocaml" {>= "4.02"}
  "dune" {>= "1.11"}
  "yojson" {>= "1.7.0"}
  "biniou" {>= "1.0.6"}
  "re"
]
```

**Comment by ygrek** [comment]
that is indeed strange, but opam files are generated by dune..

**Comment by rgrinberg** [comment]
I think it can safely be removed from the dune-project file.

**Comment by ygrek** [comment]
my bad I didn't realize opam deps are specified in dune-project (I thought dune discovers them from dune files)
