### ISSUE TITLE
Atdgen_runtime.Json_adapter.Type_field should  filter "type" field

### ISSUE THREAD

**Issue by dweil** [ahrefs/atd#219]
If I follow official documentation in https://atd.readthedocs.io/en/latest/atdgen.html#atd-annotations, the following code should be correct : 
```
type document = [
  | Image of image
  | Text of text
] <json adapter.ocaml="Atdgen_runtime.Json_adapter.Type_field">

type image = {
  url: string;
}

type text = {
  title: string;
  body: string;
}
```
Actually, I need to add a unseless fild "type : string" in both types "image" and "text".
Correction is trivial by just adding a filter in the adapter:
```
  let normalize (x : t) : t =
      match x with
      | `Assoc fields ->
          (match List.assoc type_field_name fields with
           | `String _type_ -> `List [ `String _type_; `Assoc (List.remove_assoc type_field_name fields) ]
           | exception Not_found -> x
           | _ -> x (* malformed *)
          )
      | `String _type_ as x -> x
      | malformed -> malformed
```

**Comment by cyberhuman** [comment]
> Actually, I need to add a unseless fild "type : string" in both types "image" and "text".

Can you please demonstrate why you need to add it? We use atd and this particular adapter extensively and never ran into the issue. 
AFAIK this is a feature, not a bug. See https://github.com/ahrefs/atd/blob/9a3cb984a695563c04b41cdd7a1ce9454eb40e1c/atdgen-runtime/src/json_adapter.mli#L55-L56

**Comment by dweil** [comment]
I use this adapter to translate a hierachy of JAVA classes (serialized in JSON) into OCAML variant types. For this, the json adapter described in the official documentation would be perfect. But with the current version of atd, I need to add the useless field "type : string" which will pollute my atd and my OCaml code The other solution is to write my own adapter .

But this implementation of this adapter is not compliant with the official atd documentation, this is why I logged the bug.

NB, if the issue and the pull-request, and if you really need this "type" field, you will have to write your own adapter. 

Below is the atd I had to write with the standard adapter
```
type document = [
  | Image of image
  | Text of text
] <json adapter.ocaml="Atdgen_runtime.Json_adapter.Type_field">

type image = {
  type : string;
  url: string;
}

type text = {
  type : string;
  title: string;
  body: string;
}
```

**Comment by cyberhuman** [comment]
@dweil thank you for explaining the use case in detail! But I still miss the "why you need to add it" part; that is, what happens if you don't specify "type: string" in the `image` and `text` records in your example above?

> NB, if the issue and the pull-request, and if you really need this "type" field, you will have to write your own adapter.

I'm really wary of this because this behaviour was documented and some code may already rely on it, hence this would be a breaking change. I would say it should be if you really don't need the "type" field, you have to write your own adapter. Or have this adapter in a PR to be included in atd.

**Comment by cyberhuman** [comment]
@dweil I'm still curious what the issue is. Maybe you're using `-j-strict-fields` so it fails in runtime? Otherwise the fields that you don't declare should not affect the parser in any way.

**Comment by dweil** [comment]
Yes, I forgot I was using this option -j-strict-fields.
...in the meanwhile, I found a big performance issue with the Json_adapter. Parsing time becomes quadratic and on large files, parse time is multiplied by time. This comes from the fact that when the read_with_adapter function in oj_run.ml read the JSON, then print it, then read it again, and this for each level of JSON where the adapter is used.
I'm afraid there is no solution for this performance issue. Should I log it anyway?
So I just gave up use a json_adapter.

**Comment by cyberhuman** [comment]
Thanks @dweil, this explains!
I also don't like adapters because of the performance hit, but it's more flexible than trying to implement every small feature in the core parser. You can open a new issue if you have any ideas how to improve it.
