### ISSUE TITLE
Add a way to check if annotation is valid and/or makes sense at a given position

### ISSUE THREAD

**Issue by zindel** [ahrefs/atd#227]
Inspired by https://github.com/ahrefs/atd/issues/204

For example:
```
type foo = {
  foo_bar: bool <json name="fooBar">;
}
```
It is obvious that user wanted to have the field named `fooBar` in the json output, but we have no way to report that right now. Another even more obvious case is:
```
type foo = {
  foo_bar<json nam="fooBar">: bool;
}
```
Again, `atdgen` is happy about it, while it shouldn't be ideally.

**Comment by mjambon** [comment]
An approach I would consider is one that benefits all the target languages. We define a generic iterator/visitor over the ATD tree that visits all the annotations and call a user-specified function on the corresponding node + annotation. If I counted correctly, there are 6 types of nodes in the [AST](https://github.com/ahrefs/atd/blob/master/atd/src/ast.mli) that can bear annotations. So we'd define a visitor as something like this:

```ocaml
type 'acc annot_visitor = {
  type_def: type_def -> annot -> 'acc -> 'acc;
  type_expr: type_expr -> annot -> 'acc -> 'acc;
  ... (* 4 more fields or so *)
}

type node =
  | Type_def of type_def
  | Type_expr of type_expr
  | ...

val visit_annot : 'acc annot_visitor -> node -> 'acc -> 'acc
```
With this plus some helper functions, it should be relatively painless to define which annotations are valid and where, and call the visit_annot function to collect all the invalid annotations that were found.
