### ISSUE TITLE
Add basic Python/mypy support

### ISSUE THREAD

**Issue by mjambon** [ahrefs/atd#235]
The goal is to be able to define a JSON API between OCaml and Python programs. The generated code should produce classes corresponding to ATD records. Python functions must have type annotations as supported by [mypy](http://mypy-lang.org/). The following constructs should be supported:

- [x] atomic types (unit, bool, int, float, string)
- [x] lists
- [x] records = python classes
- [x] key/value pairs = python dicts
- [x] optional fields
- [x] optional fields with default value [nice-to-have]
- [x] tuples
- [x] variants

Other subtasks:

- [x] figure out testing
- [x] document python-specific aspects
- [x] document project status and post contribution guidelines
- [x] release the software in opam

**Comment by mjambon** [comment]
I'm starting work on Python support.

**Comment by aryx** [comment]
Exciting!
