### ISSUE TITLE
atdts: ignore 'wrap' types

### ISSUE THREAD

**Issue by mjambon** [ahrefs/atd#353]
The following should not produce an error:
```
$ cat toto.atd 
type t = int wrap
$ atdts toto.atd
Error: TODO: wrap
```
The `wrap` should be ignored as we do for example in the `atdpy` implementation.

**Comment by aryx** [comment]
it's atdts, not atdpy

**Comment by mjambon** [comment]
While we're at it, let's add an option to atdcat for removing all wraps. This offers a way to fix the problem for all backends. It's also good for diffs, educational, etc.
